<div class="modal fade" id="remove" tabindex="-1" role="dialog" aria-labelledby="remove" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                Deseja realmente remover?
            </div>
            <div class="modal-body">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <a class="btn btn-danger btn-confirm">Remover</a>
            </div>
        </div>
    </div>
</div>