<div class="jumbotron">
    <h1>Trafegus Sistemas</h1>
    <p>Otimize custos a partir de indicadores. Com acesso web, o sistema possibilita
        o monitoramento em tempo real, em um único ambiente, conectando carga
        e destino de maneira segura e eficiente.</p>
    <div class="row mt-2">
        <div class="col-md-6">
            <a class="btn btn-lg btn-primary pull-right" href="<?php echo $this->url('motorista') ?>"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                MOTORISTAS</a>
        </div>
        <div class="col-md-6">
            <a class="btn btn-lg btn-primary pull-left" href="<?php echo $this->url('veiculo') ?>"><span class="glyphicon glyphicon-road" aria-hidden="true"></span>
                VEÍCULOS</a>
        </div>
    </div>
</div>